services:
  postgres-primary:
    image: postgres:16-alpine
    container_name: postgres-primary
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - primary_data:/var/lib/postgresql/data
      - ./primary/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./primary/pg_hba.conf:/etc/postgresql/pg_hba.conf
    command: >
      postgres
      -c config_file=/etc/postgresql/postgresql.conf
      -c hba_file=/etc/postgresql/pg_hba.conf

  postgres-replica-1:
    image: postgres:16-alpine
    container_name: postgres-replica-1
    restart: always
    depends_on:
      - postgres-primary
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - replica1_data:/var/lib/postgresql/data
      - ./replica/replica.sh:/docker-entrypoint-initdb.d/01-replica.sh

  postgres-replica-2:
    image: postgres:16-alpine
    container_name: postgres-replica-2
    restart: always
    depends_on:
      - postgres-primary
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - replica2_data:/var/lib/postgresql/data
      - ./replica/replica.sh:/docker-entrypoint-initdb.d/01-replica.sh

  # database: # pgadmin: general/connection
  #   container_name: database
  #   image: postgres:12-alpine
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: oop-typescript # pgadmin: general/name
  #     PGDATA: /data/postgres
  #   volumes:
  #     - ./src/databases:/var/lib/data/resources
  #     - ./src/databases/oop.sql:/docker-entrypoint-initdb.d/oop.sql
  #   ports:
  #     - 5432:5432
  #   restart: always
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - ./mongo_backup:/mongo_backup

# connect mongoDB Compass:
# Connection String: mongodb://root:root@localhost:27017/admin
# Hostname: localhost
# Port: 27017
# Username: root
# Password: root
# Authentication Database: admin
# docker exec -it mongodb mongosh -u root -p root --authenticationDatabase admin

volumes:
  primary_data:
  replica1_data:
  replica2_data:
