# ============================================================
# PostgreSQL Host-Based Authentication (pg_hba.conf)
# Environment: Docker / Dev / Staging
# Purpose    : App access + Streaming Replication
# ============================================================


# ------------------------------------------------------------
# [SECTION 1] LOCAL CONNECTIONS (Unix socket – inside container)
# ------------------------------------------------------------
# - Used by psql, init scripts, healthcheck
# - No password required
local   all             all                                     trust


# ------------------------------------------------------------
# [SECTION 2] APPLICATION / CLIENT CONNECTIONS
# ------------------------------------------------------------
# - Backend services
# - Admin tools (DBeaver, pgAdmin, psql)
# - TCP/IP connections
host    all             all             0.0.0.0/0               md5


# ------------------------------------------------------------
# [SECTION 3] STREAMING REPLICATION
# ------------------------------------------------------------
# - Required for pg_basebackupa
# - Required for WAL streaming
# - Used by replica nodes only
host    replication     postgres        0.0.0.0/0               md5
